In [12]:
from PIL import Image
import numpy as np
import sys
import os
import csv
import pandas as pd


In [13]:
def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

In [14]:
myFileList = createFileList('Data/')

Data/


In [ ]:
with open("dataset.csv","w") as f:
        fnames = ['VALUES', 'LABELS']
        writer = csv.DictWriter(f, fieldnames=fnames,delimiter=",")
        writer.writeheader()

In [33]:
LABEL = "POTHOLE"


for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    print(len(value))
    with open("dataset.csv","a") as f:
        fnames = ['VALUES', 'LABELS']
        writer = csv.DictWriter(f, fieldnames=fnames,delimiter=",")
        writer.writerow({"VALUES":value,"LABELS":LABEL})

   

Data/p 8.jpg
[ 98 108  76 ... 165 163 152]
90000
Data/p 9.jpg
[162  64  65 ...  67  47  38]
202800
Data/p 12.jpg
[79 88 79 ... 91 90 88]
388800
Data/p 1.jpg
[202 131 191 ... 131 146 154]
640920
Data/p 0.jpg
[197 196 198 ... 126 114 103]
69984
Data/p 13.jpg
[243 239 209 ...  24  46 149]
1280000
Data/p 11.jpg
[125 120 120 ... 118 136 111]
600000
Data/p 2.jpg
[162 174 164 ... 124 129  97]
245000
Data/p 14.jpg
[182 184 185 ...  92  90  89]
756000
Data/p 7.jpg
[  0   0   1 ... 136 138  59]
360000
Data/p 6.jpg
[255 255 255 ... 146 139 138]
6000000
Data/p 4.jpg
[112 117 119 ...  86  99 108]
251535


In [25]:
 # Save Greyscale values
    

[112 117 119 ...  86  99 108]
251535


In [34]:
dataFrame = pd.read_csv("dataset.csv",error_bad_lines=False)

In [37]:
dataFrame["LABELS"]

KeyError: 'LABELS'